- name: Hello World
  hosts: web 
  tasks:
  - name: print Hello DEEPTHI
    ansible.builtin.debug:
      msg: "Hello Deepthi. Dinesh loves you so much"

  - name: print Hello Dinesh
    ansible.builtin.debug:
      msg: "Hello Dinesh. Deepthi loves you so much"
          