- name: Hello world
  hosts: backend
  tasks: 

  - name: Print Hello Deepthi
    ansible.builtin.debug:
      msg: "Hello Deepthi. Dinesh loves you very much"

  - name: print Hello Dinesh
    ansible.builtin.debug:
      msg: "Hello Dinesh. Deepthi is waiting for you"
          