- name: playbook name is helloworld
  hosts: backend
  tasks:
  - name: task1 is print hello depthi
    ansible.builtin.debug:
      msg: "Hello deepthi. now deepthi is in train"

  - name: task2 is print hello dinesh 
    ansible.builtin.debug:
      msg: "hello dinesh. dinesh is in studyhall"  
      