- name: PLAY1 
  hosts: frontend 
  become: yes # Tasks ni execute cheyyadaniki kavalsina privilages istundhi 
  tasks:
  - name: installing nginx 
    ansible.builtin.package: 
      name: nginx 
      state: present 

  - name: start nginx 
    ansible.builtin.package: 
      name: nginx 
      state: started 
      enable: yes

# state: present -----> install cheyyamani
# state: absent  -----> uninstall/remove cheyyamani      
