- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: ansible
    DURATION: 10HRS
    TRAINER: sivakumar
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"
      
        