- name: PLAY-1
  hosts: local 
  connection: local 
  vars: 
    COURSE: Devops 
    DURATION: 120 Hrs 
    TRAINER: Sivakumar 
  tasks:
  - name: TASK-1 ----> print some info 
    vars:
      COURSE: Ansible 
      DURATION: 10 Hrs 
      TRAINER: Dinesh 
    ansible.builtin.debug: 
      msg: "Hello course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

  - name: TASK-2 ----> print some info 
    ansible.builtin.debug: 
      msg: "Hello course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"    
