- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter the COURSE
    private: false

  - name: DURATION
    prompt: Please enter the Duration
    private: false

  - name: TRAINER 
    prompt: Please enter the Trainer name
    private: false

  tasks:
  - name: print the variables from prompt
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"
            