- name: PLAY-1 = variables from inventory 
  hosts: local 
  connection: local 
  tasks: 
  - name: task-1 ----> print some info 
    ansible.builtin.debug: 
      msg: "Hello course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"  
      