- name: variables from inventory
  hosts: web
  tasks:
  - name: print variables from inventory
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, trainer is {{ TRAINER }}"
      