- name: check a number is graterthan 50 or not
  hosts: local
  connection: local
  vars:
    number: 30
  tasks:
  - name: print if number graterthan 50
    ansible.builtin.debug:
      msg: "given number {{ number }} is graterthan 50"
    when: number > 50

  - name: print if number is lessthan or equal to 50
    ansible.builtin.debug:
      msg: "given number {{ number }} is lessthan or equal to 50"
    when: number <= 50
