- name: loops
  hosts: local 
  connection: local 
  tasks: 
  - name: print names
    ansible.builtin.debug: 
      msg: "Hello {{ item }}"  
    loop:
    - Suresh
    - Dinesh
    - Ramesh 
    - Deepthi   