- name: installing different packages
  hosts: frontend 
  become: yes 
  tasks: 
  - name: install packages 
    ansible.builtin.package: 
      name: "{{ item }}" 
      state: present 
    loop: 
    - nginx 
    - mysql 
    - git 
    - zip  